name: React deployment 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: git config --global user.name "Exo-life"
    - run: git config --global user.email "marianareyesospina@gmail.com"
    - run: npm install 
    - run: npm run deploy

